import { afterEach, describe, expect, it, vi } from 'vitest';
import { hashPassword, PasswordBusyError, PASSWORD_HASH_PROFILE, PASSWORD_INPUT_LIMITS, PASSWORD_KDF_CONCURRENCY, validatePasswordInput, verifyPassword } from '../../apps/worker/auth/password';

const password = 'correct horse battery staple';
// Independently generated by Node 24.19 native crypto.argon2Sync('argon2id',
// { message: password, nonce: Buffer.from('00112233445566778899aabbccddeeff', 'hex'),
// parallelism: 1, tagLength: 32, memory: 19456, passes: 2 }).
const vector = '$argon2id$v=19$m=19456,t=2,p=1$ABEiM0RVZneImaq7zN3u/w$zNlY8+rVrxPryRQjL30GJ7r4tOgZLsK6gVRDMWy/cD0';

afterEach(() => vi.restoreAllMocks());

describe('native Workers Argon2id password hashes', () => {
  it('verifies an independent native Argon2id vector at the reviewed parameters', async () => {
    expect(await verifyPassword(password, vector)).toBe(true);
    expect(PASSWORD_HASH_PROFILE.memoryKiB).toBe(19_456);
    expect(PASSWORD_HASH_PROFILE.iterations).toBe(2);
    expect(PASSWORD_HASH_PROFILE.parallelism).toBe(1);
  }, 30_000);

  it('uses independent 128-bit salts and measures a local full-profile sample', async ({ task }) => {
    // Workers clocks advance on I/O, so delimit the CPU work with timer turns.
    await new Promise((resolve) => setTimeout(resolve, 0));
    const start = Date.now();
    const first = await hashPassword(password);
    await new Promise((resolve) => setTimeout(resolve, 0));
    const elapsedMs = Date.now() - start;
    task.meta['localArgon2Probe'] = {
      probe: 'argon2id-local-workers', elapsedMs,
      configuredMatrixBytes: PASSWORD_HASH_PROFILE.memoryKiB * 1024,
      peakMemoryMeasured: false,
    };
    const second = await hashPassword(password);
    expect(first).not.toBe(second);
    expect(first.split('$')[4]).not.toBe(second.split('$')[4]);
    for (const encoded of [first, second]) {
      expect(encoded).toMatch(/^\$argon2id\$v=19\$m=19456,t=2,p=1\$[A-Za-z0-9+/]{22}\$[A-Za-z0-9+/]{43}$/);
      expect(atob(encoded.split('$')[4]! + '==')).toHaveLength(16);
      expect(encoded).not.toContain(password);
    }
    expect(await verifyPassword(password, first)).toBe(true);
    expect(await verifyPassword(password + '!', first)).toBe(false);
  }, 30_000);

  it('does not trim or normalize the supplied password', async () => {
    expect(await verifyPassword(' ' + password, vector)).toBe(false);
  }, 30_000);

  it.each([
    '', null, {}, vector + '\n', ' ' + vector, vector + '=',
    vector.replace('argon2id', 'argon2i'), vector.replace('v=19', 'v=16'),
    vector.replace('m=19456', 'm=8'), vector.replace('m=19456', 'm=999999999999'),
    vector.replace('m=19456', 'm=019456'), vector.replace('t=2', 't=1'),
    vector.replace('t=2', 't=100'), vector.replace('p=1', 'p=4'),
    vector.replace('m=19456,t=2,p=1', 't=2,m=19456,p=1'),
    vector.replace('ABEiM0RVZneImaq7zN3u/w', 'ABEiM0RVZneImaq7zN3u/x'),
    vector.replace('ABEiM0RVZneImaq7zN3u/w', 'ABEiM0RVZneImaq7zN3u_w'),
    vector.replace('ABEiM0RVZneImaq7zN3u/w', 'ABEiM0RVZneImaq7zN3u/'),
    vector.slice(0, -1) + '1', vector.slice(0, -1),
  ])('rejects malformed or unsupported encodings before expensive KDF (%j)', async (encoded) => {
    expect(await verifyPassword(password, encoded)).toBe(false);
  });

  it.each([null, 42, {}, new Uint8Array([1])])('rejects non-string password inputs (%j)', async (input) => {
    await expect(hashPassword(input as string)).rejects.toThrow('Password must be a string');
    expect(await verifyPassword(input, vector)).toBe(false);
  });

  it('never logs plaintext, salt, encoded hashes or provider errors', async () => {
    const spies = (['log', 'warn', 'error', 'debug', 'info'] as const)
      .map((level) => vi.spyOn(console, level).mockImplementation(() => {}));
    expect(await verifyPassword(password, vector)).toBe(true);
    for (const spy of spies) expect(spy).not.toHaveBeenCalled();
  }, 30_000);
});

describe('password Unicode and UTF-8 input policy', () => {
  it.each([
    ['a'.repeat(6), 6, 6], ['a'.repeat(12), 12, 12], ['a'.repeat(128), 128, 128],
    ['😀'.repeat(6), 6, 24], ['😀'.repeat(12), 12, 48], ['😀'.repeat(128), 128, 512],
    ['😀'.repeat(127) + '€', 128, 511],
    ['e\u0301'.repeat(6), 12, 18], [' '.repeat(12), 12, 12],
    ['  pasted\n秘密  ', 13, 17],
  ])('accepts character/byte boundary case %# without exposing input in the title', (input, characters, utf8Bytes) => {
    expect(validatePasswordInput(input)).toEqual({ valid: true, characters, utf8Bytes });
    expect(new TextEncoder().encode(input as string)).toHaveLength(utf8Bytes as number);
  });

  it('exposes the explicit code point and byte limits', () => {
    expect(PASSWORD_INPUT_LIMITS).toEqual({ minCharacters: 6, maxCharacters: 128, maxUtf8Bytes: 512 });
    const overBytes = '😀'.repeat(128) + 'a';
    expect(new TextEncoder().encode(overBytes)).toHaveLength(513);
    // At these limits, >512 UTF-8 bytes necessarily also exceeds 128 scalar values.
    expect(validatePasswordInput(overBytes)).toEqual({ valid: false, reason: 'too_long' });
  });

  it.each([
    ['', 'too_short'], ['a'.repeat(5), 'too_short'], ['😀'.repeat(5), 'too_short'],
    ['a'.repeat(129), 'too_long'], ['😀'.repeat(129), 'too_long'],
    ['a'.repeat(1_000_000), 'too_long'],
    ['x'.repeat(12) + '\ud800', 'invalid_unicode'], ['\udfff' + 'x'.repeat(12), 'invalid_unicode'],
  ])('hash and verify consistently reject invalid input case %#', async (input, reason) => {
    expect(validatePasswordInput(input)).toEqual({ valid: false, reason });
    await expect(hashPassword(input!)).rejects.toThrow('Invalid password input');
    expect(await verifyPassword(input, vector)).toBe(false);
  });

  it('counts combining marks separately and keeps canonically equivalent strings distinct', async () => {
    expect(validatePasswordInput('é'.repeat(3))).toEqual({ valid: false, reason: 'too_short' });
    expect(validatePasswordInput('e\u0301'.repeat(6)).valid).toBe(true);
    const decomposed = 'e\u0301'.repeat(12);
    const encoded = await hashPassword(decomposed);
    expect(await verifyPassword(decomposed, encoded)).toBe(true);
    expect(await verifyPassword('é'.repeat(12), encoded)).toBe(false);
  }, 30_000);

  it('hashes and verifies the full 512-byte Unicode boundary without truncation', async () => {
    const input = '😀'.repeat(128);
    const encoded = await hashPassword(input);
    expect(await verifyPassword(input, encoded)).toBe(true);
    expect(await verifyPassword(input.slice(0, -2) + '😃', encoded)).toBe(false);
  }, 30_000);

  it('accepts spaces as content and never trims pasted passwords', async () => {
    const input = '  pasted\n秘密  ';
    const encoded = await hashPassword(input);
    expect(await verifyPassword(input, encoded)).toBe(true);
    expect(await verifyPassword(input.trim(), encoded)).toBe(false);
  }, 30_000);
});

describe('per-Worker password KDF budget', () => {
  it('holds its slot across a real async Argon2 slice and rejects excess work immediately', async () => {
    expect(PASSWORD_KDF_CONCURRENCY).toBe(1);
    // Workers clocks normally stay fixed during CPU work. Trigger exactly one
    // cooperative yield in noble's real async KDF; do not replace or weaken it.
    let firstClockRead = true;
    const clock = vi.spyOn(Date, 'now').mockImplementation(() => {
      if (firstClockRead) { firstClockRead = false; return 0; }
      return 11;
    });
    let completed = false;
    const first = hashPassword(password).then((value) => { completed = true; return value; });
    try {
      await Promise.resolve();
      expect(completed).toBe(false);
      const rejected = await Promise.allSettled([
        verifyPassword(password, vector), hashPassword(password), hashPassword(password),
      ]);
      expect(completed).toBe(false);
      for (const result of rejected) {
        expect(result.status).toBe('rejected');
        if (result.status === 'rejected') {
          expect(result.reason).toBeInstanceOf(PasswordBusyError);
          expect(result.reason.code).toBe('PASSWORD_BUSY');
        }
      }
    } finally {
      clock.mockRestore();
      await first;
    }
    expect(await verifyPassword(password, await first)).toBe(true);
  }, 30_000);

  it('shares the same slot when verification starts before hashing', async () => {
    const checking = verifyPassword(password, vector);
    const hashing = hashPassword(password);
    const [verified, rejected] = await Promise.allSettled([checking, hashing]);
    expect(verified).toEqual({ status: 'fulfilled', value: true });
    expect(rejected.status).toBe('rejected');
    if (rejected.status === 'rejected') expect(rejected.reason).toBeInstanceOf(PasswordBusyError);
    expect(await verifyPassword(password, vector)).toBe(true);
  }, 30_000);

  it('rejects invalid inputs and encoded hashes before trying to reserve a slot', async () => {
    const running = hashPassword(password);
    const invalidHash = verifyPassword(password, 'invalid encoding');
    const invalidPassword = verifyPassword('short', vector);
    const invalidNewPassword = hashPassword('short');
    const [first, second, third] = await Promise.allSettled([invalidHash, invalidPassword, invalidNewPassword]);
    expect(first).toEqual({ status: 'fulfilled', value: false });
    expect(second).toEqual({ status: 'fulfilled', value: false });
    expect(third.status).toBe('rejected');
    if (third.status === 'rejected') expect(third.reason).toBeInstanceOf(RangeError);
    await running;
    expect(await verifyPassword(password, vector)).toBe(true);
  }, 30_000);

  it('releases the slot when preparation throws after reservation', async () => {
    const failure = new Error('injected encoder failure');
    const encoder = vi.spyOn(TextEncoder.prototype, 'encode').mockImplementationOnce(() => { throw failure; });
    await expect(hashPassword(password)).rejects.toBe(failure);
    encoder.mockRestore();
    expect(await verifyPassword(password, vector)).toBe(true);
  }, 30_000);

  it('releases the slot when the actual Argon2 promise rejects', async () => {
    // A bad encoder result makes noble reject its byte-type validation. The
    // library still runs its real rejection path; this does not substitute a KDF.
    const encoder = vi.spyOn(TextEncoder.prototype, 'encode')
      .mockReturnValueOnce(new Int8Array(32) as unknown as Uint8Array<ArrayBuffer>);
    await expect(verifyPassword(password, vector)).rejects.toThrow();
    encoder.mockRestore();
    expect(await verifyPassword(password, vector)).toBe(true);
  }, 30_000);
});
