import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';

test('six-character password, unlimited concurrency, channel models and granted Key groups', async ({ page, browser }) => {
  test.setTimeout(180000);
  const connection=JSON.parse(readFileSync(join(__dirname,`../../.wrangler/e2e/connection-${process.env.SUB2API_E2E_PORT ?? '9789'}.json`),'utf8'));
  const tag=randomUUID().slice(0,8);const gptModel=`gpt-${tag}`,claudeModel=`claude-${tag}`;
  const gptName=`GPT ${tag}`,claudeName=`Claude ${tag}`,email=`groups-${tag}@example.invalid`;
  await page.goto('/');await expect(page.locator('main')).not.toContainText('协议互转');await expect(page.getByRole('img')).toHaveCount(0);
  await page.goto('/login');await page.getByLabel('邮箱',{exact:true}).fill(connection.adminEmail);await page.getByLabel('密码',{exact:true}).fill(connection.adminPassword);await page.getByRole('button',{name:'登录',exact:true}).click();
  await expect(page).toHaveURL(connection.baseURL + '/');await page.goto('/dashboard');await expect(page.locator('.amount')).toBeVisible();await expect(page.locator('main')).not.toContainText('/v1/chat/completions');
  const admin=page.context().request;const csrf=(await(await admin.get('/api/v1/settings/public')).json()).data.csrfToken;
  const headers={Origin:connection.baseURL,'X-CSRF-Token':csrf};
  async function create(path:string,data:unknown) { const response=await admin.post(path,{headers,data});expect(response.status(),await response.text()).toBe(201);return (await response.json()).data; }
  for(const publicModelId of [gptModel,claudeModel])await create('/api/v1/admin/models',{publicModelId,sellPrices:{input:'1',output:'1'},admissionMinBalanceUnits:'0',maxOutputTokens:64});
  await page.goto('/admin/channels');await page.getByRole('button',{name:'创建渠道',exact:true}).click();
  let dialog=page.getByRole('dialog');await dialog.getByLabel('名称',{exact:true}).fill(gptName);await dialog.getByLabel('上游基础 URL',{exact:true}).fill('https://e2e-upstream.example.invalid/v1');await dialog.getByLabel('上游 API Key',{exact:true}).fill('local-correction-key');
  await expect(dialog.getByLabel('并发（留空不限）',{exact:true})).toHaveValue('');await expect(dialog.getByLabel('每分钟请求数（留空不限）',{exact:true})).toHaveValue('');
  const saveBox=await dialog.getByRole('button',{name:'保存渠道',exact:true}).boundingBox();const closeBox=await dialog.getByRole('button',{name:'关闭',exact:true}).boundingBox();expect(Math.abs(saveBox!.y-closeBox!.y)).toBeLessThan(2);
  await dialog.getByRole('button',{name:'保存渠道',exact:true}).click();await expect(dialog.getByText('渠道已创建。',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'关闭',exact:true}).click();
  const gptRow=page.locator('tbody tr').filter({hasText:gptName});await expect(gptRow).toContainText('不限');await gptRow.getByRole('button',{name:'配置模型',exact:true}).click();
  dialog=page.getByRole('dialog');await expect(dialog.getByRole('combobox',{name:'公开模型',exact:true})).toBeEnabled();await dialog.getByRole('combobox',{name:'公开模型',exact:true}).selectOption(gptModel);await expect(dialog.getByLabel('上游模型名称',{exact:true})).toBeEnabled();await dialog.getByLabel('上游模型名称',{exact:true}).fill('upstream-gpt');await dialog.getByRole('button',{name:'保存模型',exact:true}).click();await expect(dialog.getByText('渠道模型已保存。',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'关闭',exact:true}).click();await expect(gptRow).toContainText('upstream-gpt');
  const channels=(await(await admin.get('/api/v1/admin/channels?limit=100')).json()).data.items;
  const gptChannel=channels.find((item:{name:string})=>item.name===gptName);expect(gptChannel.concurrencyLimit).toBe(Number.MAX_SAFE_INTEGER);expect(gptChannel.rpmLimit).toBe(Number.MAX_SAFE_INTEGER);expect(gptChannel.models[0]).toMatchObject({publicModelId:gptModel,upstreamModel:'upstream-gpt'});
  await gptRow.getByRole('button',{name:'测试连接',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('combobox',{name:'模型',exact:true})).toBeVisible();await expect(dialog.getByLabel('映射版本',{exact:true})).toHaveCount(0);await dialog.getByRole('button',{name:'关闭',exact:true}).click();
  const claudeChannel=await create('/api/v1/admin/channels',{name:claudeName,baseUrl:'https://e2e-upstream.example.invalid/v1',upstreamKey:'local-correction-key',concurrencyLimit:0,rpmLimit:60});
  await create(`/api/v1/admin/models/${claudeModel}/mappings`,{channelId:claudeChannel.id,protocol:'messages',upstreamModel:'upstream-claude',capabilities:{protocol:'messages',features:['streaming'],maxOutputTokens:64}});
  const gptGroup=await create('/api/v1/admin/groups',{name:gptName,status:'active',channelIds:[gptChannel.id]});
  const claudeGroup=await create('/api/v1/admin/groups',{name:claudeName,status:'active',channelIds:[claudeChannel.id]});
  await page.goto('/admin/users');await page.getByRole('button',{name:'创建普通用户',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('邮箱',{exact:true}).fill(email);await dialog.getByLabel('初始密码',{exact:true}).fill('abc123');await expect(dialog.getByRole('combobox',{name:'分组',exact:true})).toBeEnabled();await dialog.getByRole('combobox',{name:'分组',exact:true}).selectOption(gptGroup.id);await dialog.getByRole('button',{name:'创建用户',exact:true}).click();await expect(dialog.getByRole('button',{name:'返回用户列表',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'返回用户列表',exact:true}).click();
  const row=page.locator('tbody tr').filter({hasText:email});await expect(row).toBeVisible();await row.getByRole('button',{name:'编辑用户',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('checkbox',{name:claudeName,exact:true})).toBeEnabled();await dialog.getByRole('checkbox',{name:claudeName,exact:true}).check();await expect(dialog.getByLabel('并发（留空不限）',{exact:true})).toHaveValue('');await expect(dialog.getByLabel('每分钟请求数（留空不限）',{exact:true})).toHaveValue('');await dialog.getByRole('button',{name:'保存用户设置',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('用户设置已保存');await dialog.getByRole('button',{name:'关闭',exact:true}).click();
  const user=(await(await admin.get('/api/v1/admin/users?limit=100')).json()).data.items.find((item:{email_normalized:string})=>item.email_normalized===email);
  expect(user.allowed_group_ids.sort()).toEqual([gptGroup.id,claudeGroup.id].sort());
  const funding=await admin.post(`/api/v1/admin/users/${user.id}/balance-adjustments`,{headers:{...headers,'Idempotency-Key':randomUUID()},data:{kind:'grant',deltaUnits:'1000000',reason:'Local group integration'}});expect(funding.status()).toBe(201);
  const userContext=await browser.newContext({baseURL:connection.baseURL,ignoreHTTPSErrors:true});
  try {
    const userPage=await userContext.newPage();await userPage.goto('/login');await userPage.getByLabel('邮箱',{exact:true}).fill(email);await userPage.getByLabel('密码',{exact:true}).fill('abc123');await userPage.getByRole('button',{name:'登录',exact:true}).click();await expect(userPage).toHaveURL(connection.baseURL + '/');await userPage.goto('/dashboard');await expect(userPage.locator('.amount')).toBeVisible();
    await userPage.goto('/keys');await userPage.getByRole('button',{name:'创建 Key',exact:true}).click();const keyDialog=userPage.getByRole('dialog');await expect(keyDialog.getByRole('combobox',{name:'分组',exact:true})).toBeEnabled();await keyDialog.getByLabel('名称',{exact:true}).fill('Claude application');await keyDialog.getByRole('combobox',{name:'分组',exact:true}).selectOption(claudeGroup.id);await expect(keyDialog).toContainText(claudeModel);await expect(keyDialog).not.toContainText('禁止所有模型');await keyDialog.getByRole('button',{name:'创建 Key',exact:true}).click();const secret=keyDialog.getByLabel('完整密钥（仅显示一次）',{exact:true});await expect(secret).toBeVisible();const token=await secret.inputValue();await keyDialog.getByRole('button',{name:'已保存，关闭密钥',exact:true}).click();await expect(userPage.getByRole('table')).toContainText(claudeName);
    const bearer={Authorization:`Bearer ${token}`};const listed=await userContext.request.get('/v1/models',{headers:bearer});expect(listed.status()).toBe(200);expect((await listed.json()).data.map((m:{id:string})=>m.id)).toEqual([claudeModel]);
    const generated=await userContext.request.post('/v1/chat/completions',{headers:bearer,data:{model:claudeModel,max_tokens:16,messages:[{role:'user',content:'test'}]}});expect(generated.status(),await generated.text()).toBe(200);
    const forbidden=await userContext.request.post('/v1/chat/completions',{headers:bearer,data:{model:gptModel,messages:[{role:'user',content:'test'}]}});expect(forbidden.status()).toBe(400);
    await row.getByRole('button',{name:'编辑用户',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog.getByRole('checkbox',{name:claudeName,exact:true})).toBeEnabled();await dialog.getByRole('checkbox',{name:claudeName,exact:true}).uncheck();await dialog.getByRole('button',{name:'保存用户设置',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('用户设置已保存');await dialog.getByRole('button',{name:'关闭',exact:true}).click();
    expect((await userContext.request.get('/v1/models',{headers:bearer})).status()).toBe(401);
    await userPage.getByRole('button',{name:'编辑 / 撤销',exact:true}).click();const edit=userPage.getByRole('dialog');await expect(edit.getByRole('combobox',{name:'分组',exact:true})).toBeEnabled();await edit.getByRole('combobox',{name:'分组',exact:true}).selectOption(gptGroup.id);await edit.getByRole('button',{name:'保存 Key',exact:true}).click();await expect(edit.getByRole('status')).toContainText('Key 已保存');await edit.getByRole('button',{name:'关闭',exact:true}).click();
    const rebound=await userContext.request.get('/v1/models',{headers:bearer});expect(rebound.status()).toBe(200);expect((await rebound.json()).data.map((m:{id:string})=>m.id)).toEqual([gptModel]);
  } finally { await userContext.close(); }
});
