<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue';
import { ApiClientError } from '../../api/client.js';
import { adminAuditApi } from '../../api/admin-audit.js';
import type { AuditPage, AuditQuery } from '../../api/admin-audit.js';

const page = ref<AuditPage | null>(null); const filters = ref<AuditQuery>({}); const actor = ref(''); const action = ref(''); const targetType = ref(''); const targetId = ref(''); const operationId = ref(''); const from = ref(''); const to = ref(''); const busy = ref(false); const error = ref(''); const requestId = ref<string | null>(null); let epoch = 0;
const time = (value: number) => new Date(value).toLocaleString();
function timestamp(value: string) { if (!value) return undefined; const parsed = new Date(value).getTime(); return Number.isSafeInteger(parsed) && parsed >= 0 ? parsed : undefined; }
function changeText(value: AuditPage['items'][number]) { if (!value.redaction_valid) return '脱敏内容不可用'; if (value.changes === null) return '无可显示变更'; try { return JSON.stringify(value.changes); } catch { return '脱敏内容不可用'; } }
function apply() { const fromValue = timestamp(from.value); const toValue = timestamp(to.value); if ((from.value && fromValue === undefined) || (to.value && toValue === undefined) || (fromValue !== undefined && toValue !== undefined && fromValue > toValue)) { error.value = '请输入有效且有序的时间范围。'; return; } filters.value = { ...(actor.value.trim() ? { actorId: actor.value.trim() } : {}), ...(action.value.trim() ? { action: action.value.trim() } : {}), ...(targetType.value.trim() ? { targetType: targetType.value.trim() } : {}), ...(targetId.value.trim() ? { targetId: targetId.value.trim() } : {}), ...(operationId.value.trim() ? { operationId: operationId.value.trim() } : {}), ...(fromValue === undefined ? {} : { from: fromValue }), ...(toValue === undefined ? {} : { to: toValue }) }; void load(); }
async function load(more = false) { const ticket = ++epoch; busy.value = true; error.value = ''; requestId.value = null; try { const options: AuditQuery = more ? { ...filters.value, cursor: page.value?.nextCursor ?? null } : { ...filters.value, cursor: null }; const result = await adminAuditApi.list(options); if (ticket === epoch) page.value = more && page.value ? { ...result, items: [...page.value.items, ...result.items] } : result; } catch (cause) { if (ticket === epoch) { error.value = cause instanceof Error ? cause.message : '审计读取失败。'; requestId.value = cause instanceof ApiClientError ? cause.request_id : null; } } finally { if (ticket === epoch) busy.value = false; } }
function reset() { actor.value = ''; action.value = ''; targetType.value = ''; targetId.value = ''; operationId.value = ''; from.value = ''; to.value = ''; filters.value = {}; void load(); }
onMounted(() => { void load(); }); onBeforeUnmount(() => { epoch++; });
</script>

<template>
  <section><h1>管理审计</h1><form class="filters" @submit.prevent="apply"><label>操作者 ID<input v-model="actor" maxlength="128" autocomplete="off" /></label><label>动作<input v-model="action" maxlength="64" autocomplete="off" /></label><label>目标类型<input v-model="targetType" maxlength="64" autocomplete="off" /></label><label>目标 ID<input v-model="targetId" maxlength="128" autocomplete="off" /></label><label>操作 ID<input v-model="operationId" maxlength="128" autocomplete="off" /></label><label>开始时间<input v-model="from" type="datetime-local" /></label><label>结束时间<input v-model="to" type="datetime-local" /></label><button type="submit" :disabled="busy">查询</button><button type="button" class="secondary" @click="reset">清空</button></form>
    <p v-if="busy" role="status">正在读取审计…</p><p v-if="error" role="alert">{{ error }} <small v-if="requestId">请求编号：{{ requestId }}</small><button type="button" @click="load()">重试</button></p><p class="empty-state" v-if="!busy && !error && page?.items.length === 0">暂无审计记录。</p><div v-if="page?.items.length" class="table-scroll"><table><caption>脱敏审计记录</caption><thead><tr><th>时间</th><th>操作者</th><th>动作</th><th>目标</th><th>操作 ID</th><th>脱敏变更</th></tr></thead><tbody><tr v-for="entry in page.items" :key="entry.id"><td>{{ time(entry.created_at) }}</td><td>{{ entry.actor_id }}</td><td>{{ entry.action }}</td><td>{{ entry.target_type }}<br /><code>{{ entry.target_id }}</code></td><td><code>{{ entry.operation_id }}</code></td><td><code>{{ changeText(entry) }}</code></td></tr></tbody></table></div><button v-if="page?.nextCursor" type="button" :disabled="busy" @click="load(true)">加载更多</button>
  </section>
</template>

<style scoped>
.filters { display: flex; flex-wrap: wrap; align-items: end; gap: 12px; background: #fff; border: 1px solid var(--line); border-radius: 8px; padding: 18px; margin: 20px 0; }label { display: grid; gap: 7px; min-width: 130px; }input { padding: 9px; border: 1px solid #cfd0c6; border-radius: 5px; font: inherit; }.secondary { background: #fff; color: var(--ink); }.table-scroll { overflow-x: auto; margin: 24px 0; }table { width: 100%; border-collapse: collapse; background: #fff; }th,td { padding: 14px; text-align: left; vertical-align: top; border-bottom: 1px solid var(--line); overflow-wrap: anywhere; }caption { text-align: left; padding-bottom: 12px; }small { color: var(--muted); }code { white-space: pre-wrap; overflow-wrap: anywhere; }button { margin: 8px 8px 8px 0; }
</style>
