<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue';
import { ApiClientError } from '../../api/client.js';
import { adminBillingApi } from '../../api/admin-billing.js';
import { formatUnitsToUsd } from '../../api/billing.js';
import type { BillingKind, BillingPage, BillingQuery } from '../../api/billing.js';
import type { BalanceReconciliationPage } from '../../api/admin-billing.js';

const page = ref<BillingPage | null>(null); const kind = ref<'' | BillingKind>(''); const userId = ref(''); const requestFilter = ref(''); const busy = ref(false); const error = ref(''); const requestId = ref<string | null>(null); let epoch = 0;
const reconciliation = ref<BalanceReconciliationPage | null>(null); const reconciliationBusy = ref(false); const reconciliationError = ref(''); const reconciliationCursor = ref<string | null>(null);
const labels: Record<BillingKind, string> = { consumption: '模型消费', grant: '管理员授额', adjustment: '余额调整' };
const money = (value: string) => { try { return `${formatUnitsToUsd(value)} USD`; } catch { return '金额未知'; } };
function query(more = false): BillingQuery { const base: BillingQuery = { ...(kind.value ? { kind: kind.value } : {}), ...(userId.value.trim() ? { userId: userId.value.trim() } : {}), ...(requestFilter.value.trim() ? { requestId: requestFilter.value.trim() } : {}) }; return more ? { ...base, cursor: page.value?.nextCursor ?? null } : { ...base, cursor: null }; }
async function load(more = false) { const ticket = ++epoch; busy.value = true; error.value = ''; requestId.value = null; try { const result = await adminBillingApi.list(query(more)); if (ticket === epoch) page.value = more && page.value ? { ...result, items: [...page.value.items, ...result.items] } : result; } catch (cause) { if (ticket === epoch) { error.value = cause instanceof Error ? cause.message : '管理账单读取失败。'; requestId.value = cause instanceof ApiClientError ? cause.request_id : null; } } finally { if (ticket === epoch) busy.value = false; } }
async function loadReconciliation(more = false) { reconciliationBusy.value = true; reconciliationError.value = ''; try { const result = await adminBillingApi.reconciliation(more ? reconciliationCursor.value : null); reconciliation.value = more && reconciliation.value ? { ...result, items: [...reconciliation.value.items, ...result.items] } : result; reconciliationCursor.value = result.nextCursor; } catch (cause) { reconciliationError.value = cause instanceof Error ? cause.message : '余额核对读取失败。'; } finally { reconciliationBusy.value = false; } }
const usd = (value: string) => { try { return `${formatUnitsToUsd(value)} USD`; } catch { return '金额未知'; } };
onMounted(() => { const params = new URLSearchParams(window.location.search); requestFilter.value = params.get('requestId') ?? ''; void load(); void loadReconciliation(); }); onBeforeUnmount(() => { epoch++; });
</script>

<template>
  <section><h1>管理账单</h1><form class="filters" @submit.prevent="load()"><label>类型<select v-model="kind"><option value="">全部</option><option value="consumption">模型消费</option><option value="grant">管理员授额</option><option value="adjustment">余额调整</option></select></label><label>用户 ID<input v-model="userId" maxlength="128" autocomplete="off" /></label><label>请求 ID<input v-model="requestFilter" maxlength="128" autocomplete="off" /></label><button type="submit" :disabled="busy">查询 / 刷新</button></form>
    <p v-if="busy" role="status">正在读取账单…</p><p v-if="error" role="alert">{{ error }} <small v-if="requestId">请求编号：{{ requestId }}</small><button type="button" @click="load()">重试</button></p><p class="empty-state" v-if="!busy && !error && page?.items.length === 0">暂无账单记录。</p><div v-if="page?.items.length" class="table-scroll"><table><caption>全局账单</caption><thead><tr><th>类型 / 用户</th><th>金额变化</th><th>请求</th><th>原因 / 操作者</th><th>时间</th></tr></thead><tbody><tr v-for="entry in page.items" :key="entry.id"><td>{{ labels[entry.kind] }}<br /><small>{{ entry.userId }}</small></td><td><strong>{{ money(entry.deltaUnits) }}</strong></td><td>{{ entry.requestId ?? '—' }}</td><td>{{ entry.reason ?? (entry.kind === 'consumption' ? '模型消费' : '—') }}<br /><small>{{ entry.createdBy ?? '系统' }}</small></td><td>{{ new Date(entry.createdAt).toLocaleString() }}</td></tr></tbody></table></div><button v-if="page?.nextCursor" type="button" :disabled="busy" @click="load(true)">加载更多</button>
    <h2>余额与账单核对</h2><p v-if="reconciliationBusy" role="status">正在读取余额核对…</p><p v-if="reconciliationError" role="alert">{{ reconciliationError }} <button type="button" @click="loadReconciliation()">重试核对</button></p><p class="empty-state" v-if="!reconciliationBusy && !reconciliationError && reconciliation?.items.length === 0">暂无余额核对记录。</p><div v-if="reconciliation?.items.length" class="table-scroll"><table><caption>余额核对结果</caption><thead><tr><th>用户</th><th>当前余额</th><th>账单合计</th><th>差额</th><th>状态</th></tr></thead><tbody><tr v-for="item in reconciliation.items" :key="item.userId"><td>{{ item.userId }}<br /><small>{{ item.entryCount }} 条账单</small></td><td :class="{ negative: item.negativeBalance }">{{ usd(item.balanceUnits) }}</td><td>{{ usd(item.ledgerUnits) }}</td><td>{{ usd(item.differenceUnits) }}</td><td>{{ item.negativeBalance ? '负余额' : item.matches ? '一致' : '存在差额' }}</td></tr></tbody></table></div><button v-if="reconciliation?.nextCursor" type="button" :disabled="reconciliationBusy" @click="loadReconciliation(true)">加载更多核对</button>
  </section>
</template>

<style scoped>
.filters { display: flex; flex-wrap: wrap; align-items: end; gap: 12px; background: #fff; border: 1px solid var(--line); border-radius: 8px; padding: 18px; margin: 20px 0; }label { display: grid; gap: 7px; }input,select { padding: 9px; border: 1px solid #cfd0c6; border-radius: 5px; font: inherit; }.table-scroll { overflow-x: auto; margin: 24px 0; }table { width: 100%; border-collapse: collapse; background: #fff; }th,td { padding: 14px; text-align: left; vertical-align: top; border-bottom: 1px solid var(--line); overflow-wrap: anywhere; }caption { text-align: left; padding-bottom: 12px; }small { color: var(--muted); }.negative { color: var(--danger); }button { margin: 8px 8px 8px 0; }
</style>
