-- Generated by scripts/generate-model-seeds.mjs. Reference prices checked 2026-09-10.
-- Flat platform selling prices, not automatic provider tier pricing. Preserve existing configuration.
INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5','active','{"input":"1.25","output":"10","cacheRead":"0.125"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5-mini','active','{"input":"0.25","output":"2","cacheRead":"0.025"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5-nano','active','{"input":"0.05","output":"0.4","cacheRead":"0.005"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5.1','active','{"input":"1.25","output":"10","cacheRead":"0.125"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5.2','active','{"input":"1.75","output":"14","cacheRead":"0.175"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5.3-codex','active','{"input":"1.75","output":"14","cacheRead":"0.175"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5.4','active','{"input":"2.5","output":"15","cacheRead":"0.25"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5.4-mini','active','{"input":"0.75","output":"4.5","cacheRead":"0.075"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5.4-nano','active','{"input":"0.2","output":"1.25","cacheRead":"0.02"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5.5','active','{"input":"5","output":"30","cacheRead":"0.5"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5.6','active','{"input":"4","output":"20","cacheRead":"0.4","cacheWrite":"5"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5.6-sol','active','{"input":"4","output":"20","cacheRead":"0.4","cacheWrite":"5"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5.6-terra','active','{"input":"2","output":"12","cacheRead":"0.2","cacheWrite":"2.5"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-5.6-luna','active','{"input":"0.2","output":"1.2","cacheRead":"0.02","cacheWrite":"0.25"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('gpt-6-astra','active','{"input":"10","output":"50","cacheRead":"1","cacheWrite":"12.5"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('claude-sonnet-4-6','active','{"input":"3","output":"15","cacheRead":"0.3","cacheWrite":"3.75","cacheWrite5m":"3.75","cacheWrite1h":"6"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('claude-opus-4-6','active','{"input":"5","output":"25","cacheRead":"0.5","cacheWrite":"6.25","cacheWrite5m":"6.25","cacheWrite1h":"10"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('claude-opus-4-7','active','{"input":"5","output":"25","cacheRead":"0.5","cacheWrite":"6.25","cacheWrite5m":"6.25","cacheWrite1h":"10"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('claude-opus-4-8','active','{"input":"5","output":"25","cacheRead":"0.5","cacheWrite":"6.25","cacheWrite5m":"6.25","cacheWrite1h":"10"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('claude-sonnet-5','active','{"input":"2","output":"10","cacheRead":"0.2","cacheWrite":"2.5","cacheWrite5m":"2.5","cacheWrite1h":"4"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('claude-opus-5','active','{"input":"5","output":"25","cacheRead":"0.5","cacheWrite":"6.25","cacheWrite5m":"6.25","cacheWrite1h":"10"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('claude-fable-5','active','{"input":"10","output":"50","cacheRead":"1","cacheWrite":"12.5","cacheWrite5m":"12.5","cacheWrite1h":"20"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;

INSERT INTO models (public_model_id,status,sell_prices_json,price_version,admission_min_balance_units,max_output_tokens,default_output_tokens,created_at,updated_at)
VALUES ('claude-mythos-5','active','{"input":"10","output":"50","cacheRead":"1","cacheWrite":"12.5","cacheWrite5m":"12.5","cacheWrite1h":"20"}',1,0,128000,4096,CAST(strftime('%s', 'now') AS INTEGER) * 1000,CAST(strftime('%s', 'now') AS INTEGER) * 1000)
ON CONFLICT(public_model_id) DO NOTHING;
